#! /usr/bin/env bash
# vi:set ft=sh
# a simple get request, 
curl -s 'http://localhost:8080/____/delete/mysql/test/mysql_echo.dot?from=thequerystring' > /dev/null 2>&1
curl -s -X POST 'http://localhost:8080/____/delete/mysql/test/mysql_echo.dot?from=thequerystring' > /dev/null 2>&1
curl -s 'http://localhost:8080/____/delete/mysql/test/mysql_echo.dot?from=thequerystring' --data 'andfrom=thebody' > /dev/null 2>&1
curl -v 'http://localhost:8080/mysql/test/mysql_echo.dot?from=thequerystring' 2>&1 | egrep 'thequerystring|x-cache-key' | sed -E -e 's/user-agent=curl\/[0-9]\.[0-9]{1,2}\.[0-9]{1,2} //g'
# same thing only as a post
curl -v -X POST 'http://localhost:8080/mysql/test/mysql_echo.dot?from=thequerystring' 2>&1 | egrep 'thequerystring|x-cache-key' |  sed -E -e 's/user-agent=curl\/[0-9]\.[0-9]{1,2}\.[0-9]{1,2} //g'
# a post with the same URL, along with some body data, all of these should vary the cache key
curl -v 'http://localhost:8080/mysql/test/mysql_echo.dot?from=thequerystring' --data 'andfrom=thebody' 2>&1 | egrep 'thequerystring|x-cache-key' |  sed -E -e 's/user-agent=curl\/[0-9]\.[0-9]{1,2}\.[0-9]{1,2} //g'
